#Configuation for robot Odom EKF
frequency: 50
two_d_mode: true
publish_tf: true

predict_to_current_time: true
# transform_time_offset: 1

odom_frame: odom
base_link_frame: base
world_frame: odom

# X,   Y,   Z
# r,   p,   y,
# X',  Y',   Z'
# r',  p',  y'
# X'', Y'', Z''

odom0: /go1_controller/odom
odom0_config: [false, false, false,
               false, false, false,
               true, false, false,
               false, false, false,
               false, false, false]      
odom0_differential: false
odom0_queue_size: 10

imu0: /go1_controller/imu/data
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,     # Ï‰z
              true,  false, false]    # ax, ay
imu0_differential: false
imu0_queue_size: 10