apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ros-network.yml
  - ros-master.yml
  - mediamtx.yml
  - video-receiver.yml
  - go1-base.yml
  - lidar-drivers.yml
  - go1-navigation.yml
  - video-streamer.yml
  - vizanti.yml
  - digital-replica.yml
